### ISSUE TITLE
"Invalid URL /rewards"

### ISSUE THREAD

**Issue by shatteredhalo** [Fabbi/autoshift#31]
The script seems to be throwing some kind of error while redeeming keys for BLPS I believe. Below is the output from start to script termination. Let me know if you need any further info. Thank you for your time and work on this project!

C:\autoshift-master>auto.py --game bl bl2 bl3 blps --platform steam
Parsing BL   keys...done. (no new Keys)
You have 5 golden BL keys to redeem for STEAM
Parsing BL2  keys...done. (no new Keys)
You have 3 golden BL2 keys to redeem for STEAM
Parsing BL3  keys...done. (no new Keys)
You have 8 golden BL3 keys to redeem for STEAM
Parsing BLPS keys...done. (no new Keys)
You have 184 golden BLPS keys to redeem for STEAM
[1;36m2020-10-16 01:15:52,716 [[1;34mINFO[0m[1;36m] [0m    [0mTrying to redeem 5 Golden Keys (SRCBJ-5KXFF-5T6K3-33BBB-WBF6H)
[1;36m2020-10-16 01:15:53,671 [[1;34mINFO[0m[1;36m] [0m    [0mPlease wait
[1;36m2020-10-16 01:15:54,308 [[1;34mINFO[0m[1;36m] [0m    [0mPlease wait
[1;36m2020-10-16 01:15:54,401 [[1;34mINFO[0m[1;36m] [0m    [0mRedeemed 5 Golden Keys
[1;36m2020-10-16 01:15:54,402 [[1;34mINFO[0m[1;36m] [0m    [0mRedeeming another 195 Keys
[1;36m2020-10-16 01:15:54,402 [[1;34mINFO[0m[1;36m] [0m    [0mTrying to redeem 3 Golden Keys (ZFKJ3-TT3BB-JTBJT-T3JJT-JWX9H)
[1;36m2020-10-16 01:15:55,179 [[1;34mINFO[0m[1;36m] [0m    [0mPlease wait
[1;36m2020-10-16 01:15:55,753 [[1;34mINFO[0m[1;36m] [0m    [0mPlease wait
[1;36m2020-10-16 01:15:56,339 [[1;34mINFO[0m[1;36m] [0m    [0mPlease wait
[1;36m2020-10-16 01:15:56,960 [[1;34mINFO[0m[1;36m] [0m    [0mPlease wait
[1;36m2020-10-16 01:15:57,538 [[1;34mINFO[0m[1;36m] [0m    [0mPlease wait
[1;36m2020-10-16 01:15:58,109 [[1;34mINFO[0m[1;36m] [0m    [0mPlease wait
Traceback (most recent call last):
  File "C:\autoshift-master\auto.py", line 218, in <module>
    main(args)
  File "C:\autoshift-master\auto.py", line 188, in main
    redeemed = redeem(key, platform)
  File "C:\autoshift-master\auto.py", line 58, in redeem
    status = client.redeem(key.key, platform)
  File "C:\autoshift-master\shift.py", line 140, in redeem
    status, result = self.__redeem_form(form_data)
  File "C:\autoshift-master\shift.py", line 317, in __redeem_form
    r2 = self.client.get(redirect)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Username\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/rewards': No schema supplied. Perhaps you meant http:///rewards?

**Comment by Fabbi** [comment]
that's strange. It seems that the Shift Plattform wanted to redirect you to `/rewards`.. What happenes if you rerun it only using the `blps` game?

**Comment by Fabbi** [comment]
no answer => assume this was a one-time bug
