### ISSUE TITLE
SQLite objects created in a thread can only be used in that same thread

### ISSUE THREAD

**Issue by Wyrrrd** [Fabbi/autoshift#42]
Hi, I have an error in the latest docker version.

To me it is unclear why the thread ID changed, might be the intended code, might also be the original thread crashing due to low resources (I limit container CPU and memory).

<details><summary>Debug Log Excerpt</summary>

```
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140258964301632 and this is thread id 140258919384832.
Job "main (trigger: interval[1:05:00], next run at: 2022-06-29 09:16:40 CEST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "//./autoshift/auto.py", line 175, in main
    all_keys = query_keys(args.games, args.platforms)
  File "//./autoshift/auto.py", line 77, in query_keys
    keys = list(query.db.get_keys(None, None))
  File "/autoshift/query.py", line 285, in get_keys
    ex = self.execute(cmd, params)
  File "/autoshift/query.py", line 199, in execute
    return self.__c.execute(sql, parameters)
```
</details>

**Comment by Torsdan** [comment]
Just checked mine, getting the same error. My dockers aren't limited.

**Comment by Fabbi** [comment]
oh, I think I know what's happening. 
The scheduler runs the code periodically and the database isn't reopened properly. I'll fix that later today.

**Comment by Fabbi** [comment]
I pushed a fix. Hope, this was the last bug for now 😃

**Comment by Torsdan** [comment]
It is working now, thank you.
